// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRHT2iRBYVoZ59MS5f2SzDG6FmoYctSuU',
    appId: '1:367300471060:web:5e06ebd17000777fda7a01',
    messagingSenderId: '367300471060',
    projectId: 'pettiva-af8e4',
    authDomain: 'pettiva-af8e4.firebaseapp.com',
    databaseURL: 'https://pettiva-af8e4-default-rtdb.firebaseio.com',
    storageBucket: 'pettiva-af8e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANW3VQW0WvDnXyoldceN_pUI3IGEdtpOs',
    appId: '1:367300471060:android:aef9fc36d81f0d60da7a01',
    messagingSenderId: '367300471060',
    projectId: 'pettiva-af8e4',
    databaseURL: 'https://pettiva-af8e4-default-rtdb.firebaseio.com',
    storageBucket: 'pettiva-af8e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh9sYs7kF-zf7XrvgB-itCRxpC81nr_Pg',
    appId: '1:367300471060:ios:7de048dd7b5b8fe2da7a01',
    messagingSenderId: '367300471060',
    projectId: 'pettiva-af8e4',
    databaseURL: 'https://pettiva-af8e4-default-rtdb.firebaseio.com',
    storageBucket: 'pettiva-af8e4.firebasestorage.app',
    iosBundleId: 'com.example.pettivaV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh9sYs7kF-zf7XrvgB-itCRxpC81nr_Pg',
    appId: '1:367300471060:ios:7de048dd7b5b8fe2da7a01',
    messagingSenderId: '367300471060',
    projectId: 'pettiva-af8e4',
    databaseURL: 'https://pettiva-af8e4-default-rtdb.firebaseio.com',
    storageBucket: 'pettiva-af8e4.firebasestorage.app',
    iosBundleId: 'com.example.pettivaV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRHT2iRBYVoZ59MS5f2SzDG6FmoYctSuU',
    appId: '1:367300471060:web:fd154588ddd108bfda7a01',
    messagingSenderId: '367300471060',
    projectId: 'pettiva-af8e4',
    authDomain: 'pettiva-af8e4.firebaseapp.com',
    databaseURL: 'https://pettiva-af8e4-default-rtdb.firebaseio.com',
    storageBucket: 'pettiva-af8e4.firebasestorage.app',
  );
}
